### ISSUE TITLE
Consensus on what documentation style, and tool, to use in C++ code

### ISSUE THREAD

**Issue by Fluxie** [Rantanen/intercom#24]
I don't have a preference at the moment. But we should choose one to guarantee uniform style and the ability to generate reasonable documentation.

Alternatives:

[Doxygen](http://www.stack.nl/~dimitri/doxygen/), [Doxygen Bootstrapped](https://github.com/Velron/doxygen-bootstrapped)
[Cldoc](http://jessevdk.github.io/cldoc/)

Discussion in Stack Overflow:
https://stackoverflow.com/questions/2323074/doxygen-alternative-for-c
https://stackoverflow.com/questions/30954841/why-is-doxygen-so-unfriendly-to-mobiles

**Comment by Rantanen** [comment]
I just surprised myself by falling in favor of Markdown (Boostrapped).

The Cldoc [example](http://jessevdk.github.io/cldoc/example/) seems to work really badly with back/forward browser navigation. Also I'm not a fan of the fully JavaScript based navigation.

Doxygen is also better supported with more options for output - so using a Doxygen compatible comment style in C++ code means we keep our options for output formatting wider.

**Comment by Rantanen** [comment]
I looked further into this. "Doxygen style" is a bit broad concept.

Looking into the possible doxygen-supported styles, I think using `///` format would make most sense as this mirrors that of Rust - especially since Doxygen has Markdown support as well.

```C++
/// COM smart pointer
///
/// Implements COM reference counting and query interface mechanics.
/// Note that `add_ref` and `release` should not be called manually for
/// items handled through the `ComPtr` type.
class ComPtr
{
    public:  // What's the indentation of this? Is there a majority style?

        /// ComPtr constructor. Wraps an existing raw pointer.
        ComPtr( void* ptr );
}
```

The downside of this style is that at least Visual Studio won't autofill `///`'s on new line. Does VSCode do it? I know Vim does it so I'm covered. :)

If we go with `/* .. */`-derived style, I believe using the JavaDoc format would make sense, given how popular JavaDoc and its derivatives (JSDoc) are in general. Also both VS and Vim insist on auto-filling leading `*`'s on new line. I'd guess this is a common feature in IDEs (thanks to the popularity of JavaDoc/etc.):

```C++
/**
 * COM smart pointer
 *
 * Implements COM reference counting and query interface mechanics.
 * Note that `add_ref` and `release` should not be called manually for
 * items handled through the `ComPtr` type.
 */
class ComPtr
{
    // ...
}
```
